### ISSUE TITLE
Project setup instructions

### ISSUE THREAD

**Issue by andy-novikov** [wrightflyer/XFM#1]
please describe how to build/use this project.
prerequisites, requirements, commands

**Comment by wrightflyer** [comment]
The joy of Python is that it is an interpreted language. There is no "building" as such. With python installed on your PC it's literally as simple as just typing "python xfm.py" in a command prompt/terminal and what's even nicer is it should work the same whether it is Windows or Linux (though I did all the development in Windows and haven't tried Linux)

While I tried to make it work in a standard Python installation (so all the graphics are done with Tcl/Tkinter that comes as standard with Python) the fact is that Python doesn't have MIDI support as standard so you will have to do some "pip install"s to add the additional modules. But, again, one of the nice things about Python is that almost everything you ever need to add is just one" pip install" away.

I'll push some info into the README.md to explain all this and show what pip install's are needed.

**Comment by wrightflyer** [comment]
Main Readme now has lots of detail.
