### ISSUE TITLE
How to send back to XFM

### ISSUE THREAD

**Issue by wkistler** [wrightflyer/XFM#2]
This tool looks amazing!  I have it up and running, and I can get a patch from xfm and save/load json files without too much trouble, but I can't for the life of me figure out how to transmit a changed patch back to the XFM.

Thanks for what you're doing!

**Comment by wrightflyer** [comment]
See my extensive posts about this in the Sonicware Liven group on Facebook (Sonicware's main forum for support) :

https://www.facebook.com/groups/sonicwareliven/?ref=share

The fact is that at present the Sysex export of patches are "protected" with a CRC so if the data is changed it's not possible to send it back (this is to protect against upload of corrupt data).

I asked Sonicware for the algorithm to recalculate CRC but they said that it was "secure" and they couldn't give it to me. But what they did promise was that in an XFM firmware update they'd make it easier for edited patches to be sent back.

For the time being I've stopped work on the editor as I can't really progress until it's possible to send patches back.

Sonicware have been so busy working on SmplTrek and LoFi 12 that they are presumably too busy to work on XFM but once all the post release bug fixes and improvements are done to those hopefully they'll have time to change XFM

**Comment by wkistler** [comment]
Thanks for the detailed response!  I kind of suspected that the functionality wasn't just hiding somewhere.  I'll keep an eye on the facebook group, and hopefully something will come of it.  I have some patches for some other 4 op FM synths that are either easily readable XML or just have plain text accompanying the syx files.  My eventual hope is to make a little script that will convert them to a json formatted like your program and be able to load them on easily (instead of trying to dial in each parameter by hand).  

Thanks again, I'll be keeping an eye out.

**Comment by wrightflyer** [comment]
It's not complete yet but I now know how to recalculate CRC so I should be able to finish code to send edited data back

**Comment by wkistler** [comment]
Hero!  I'm sure you'll post when you're done.  I'm looking forward to it.

**Comment by wrightflyer** [comment]
Hi. So Sonicware have now released firmware 3.0.46 for XFM so the editor can now be used in both directions. Get the first true release here:

https://github.com/wrightflyer/XFM/releases/tag/v1.0-release

As such I'm going to close this now ;-)
