### ISSUE TITLE
routing doesn't appear to update

### ISSUE THREAD

**Issue by Colinb123** [wrightflyer/XFM#3]
**Describe the bug**
Routing not updatings

**To Reproduce**

Click on routing. nothing happens but below is the error

**Expected behavior**
Chris lodys wonderful sketch

Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "xfm.py", line 581, in toggleNums
  File "xfm.py", line 699, in draw
  File "tkinter\__init__.py", line 2823, in create_line
  File "tkinter\__init__.py", line 2805, in _create
_tkinter.TclError: error reading bitmap file ".\stipple\stip0.xbm"

**Desktop (please complete the following information):**

Win 11 21H2 22000.1574

**Comment by Colinb123** [comment]
I just copied the stipple folder from the source code and copied it into my route directory of the .exe install file. Now it works. Maybe the files are missing from the install package?  thanks

**Comment by wrightflyer** [comment]
It was indeed an omission from the packaging process. Hopefully now corrected in this release:

https://github.com/wrightflyer/XFM/releases/tag/v1.01-beta1

(see release notes - there are other changes too)
